language: node_js
sudo: required
node_js:
  - "node" 
services:
  - mysql
  - docker
  env:
    global:
    - secure: "nPsg+DqYM71vItgvlNowxVZ076KeJt0idQCkZkc2CPIkJQL+DT6kVFjKzy6cUW8HRm13qFUda9xV38fdj008Ce80Rh1PYYKhkDaAEW+xvIro0r9Bp+eFRLTMN7uXAGc2u4LBUZshqDcDgY9ZTV43mzxy6Y5uGo/tPacaXO0MvTYEt0/y9XKN6LY0jymQJmj69J0rgjREVUxUwFDuKO7kG2E9E4mU87IF2IaqGjLsS85xux4U7ubPSv/kbDQ1Pb8FM65sDocvsyUIHY1ov2QLEDwZkow9DhnAmtfG6MXAxcST3afwfiQKdzQQ1NJRBm92C9bssSCHOBituQHmS9zPVGa20zriC9nDAvpv+MjY7T6MLaezcK40TYPzJ4xRNr99Ie8x8IwrNGfsaqdIOGQcY3btp/OG7TATJIDksP7Ygc2QMosvnEEqmB/ifEp6B0rOGHt1JfW18PaymzvHNPjImAeGZr9wNLz0AsYPmtMepsVrvqvwsXb2aFsz4yFD0ZOkiN2CW383jqjNUWVWN7DxwKC18zSx6ue1mIS6Ade5NUrOOuVg9uLkJ7lh0wFsKq91d/Vex8k4IdN/TlMW6rldGnJmB8hAq+iLFhqUO6deeX3TzMFCqmLdw/hbG6ZB3lzW/MximdGq/RjW+IyHhdbaDfBZfSQEbbTYMytdUdKRTQA="
    - secure: "r5oIWzQEIrDatBnLYoE31opAqCodxS1ozf+m1/c9uS/oL5vtLGvvCbdZYXxdXmb1z6sbGQEKOqaNekpavtLx5O16JBTJNavYUN75ucjI4qKASwEll1xaJwOuOlUJsDC9Ge2fKg8voH1B83w/MrN1qLVzINwwkw7Nd3BI307fBmthvRCrTTdzaqD/2q6LwAA1n4IyZbtsVegvB3/BycNH4raFyFEAF/Muq4kd8n3cy6ZVv3+9AJDoHx1mtkbJSvBgU9A+G+H8f+9e3F6aGJd4rHazBADrnv5Z1dn92u+8LegXM3eGkw+AFyxlyR+aZX1ZbPu1eiMheKOUN0H56piE3QXxVgNesprCaIPBJ4yhM+D94ivSkLgbalZ7yIjkRP5NUMtYrNQCbeS/tEpkVYh6azOugcD2fjYh1YtrHr4v1J86WF8gPOTbA5L+3bqgbrqSRweCxTsT06C0GSsiNrtnzyp4v7lKNcfoTQ/P2nBlzD528y1AtSYKA8hXBx/h+Ux6BBZcJKDeY0U4+Mf5mfbaWNrXHG3HxwNo4hr+6G+e/GvvW/r9Cmze6Dndt07FgT6pqjB6myVHf+XcY7lD0a6SMXXoLoMWJLaRXRcvMocTEF2E/f5eoMboSV4Ra7W3Tuiqkd8ceQLlwUYb6AlXPmcQLo/lYZYdm9pDFmlg3J5OZBw="

before_install: 
  - mysql -e 'DROP DATABASE IF EXISTS votaciones_splc'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS votaciones_splc;'
  - mysql -u root --default-character-set=utf8 votaciones_splc < db_dump/script_create_votaciones_splc.sql
  - mysql -u root --default-character-set=utf8 votaciones_splc < db_dump/splc2017.sql
  - mysql -u root --default-character-set=utf8 votaciones_splc < db_dump/script_populate_votaciones_splc.sql
install:
  - npm install
  - npm add request
  - npm install mysql
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('your_password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
cache:
 directories:
    - node_modules
script: 
  - npm run test
  - bash build_and_upload_docker.sh

  branches:
  only:
  - master
  - develop

