language: node_js
sudo: required
node_js:
  - "node" 
services:
  - mysql
  - docker
before_install: 
  - mysql -e 'DROP DATABASE IF EXISTS votaciones_splc'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS votaciones_splc;'
  - mysql -u root --default-character-set=utf8 votaciones_splc < db_dump/script_create_votaciones_splc.sql
  - mysql -u root --default-character-set=utf8 votaciones_splc < db_dump/splc2017.sql
  - mysql -u root --default-character-set=utf8 votaciones_splc < db_dump/script_populate_votaciones_splc.sql
install:
  - npm install
  - npm add request
  - npm install mysql
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('your_password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
cache:
 directories:
    - node_modules
script: 
  - npm run test
 # - bash build_and_upload_docker.sh


branches:
  only:
  - master
  - develop
  
  
  
  
