language: node_js
sudo: required
node_js:
  - "8" 
  - "9" 
  - "node"
install:
  - npm install
script: npm index index.js
services:
  - mysql
  - docker
  - mariadb
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('your_password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
before_install: 
  - mysql -e 'DROP DATABASE IF EXISTS votaciones_splc'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS votaciones_splc;'
  - mysql -u root --default-character-set=utf8 votaciones_splc < db_dump/script_create_votaciones_splc.sql
  - mysql -u root --default-character-set=utf8 votaciones_splc < db_dump/splc2017.sql

